hiddenSymmetries/simsopt

- .gitignore
- examples/logger_example.py
- setup.cfg
- src/simsopt/util/log_config.yaml
- src/simsopt/util/logging.py
This PR introduces logging functionality that is simple and consistent to use for both serial and mpi jobs.
For serial jobs: 
```python 
from simstop.util.log import initialize_logging
initialize_logging(filename="serial.log")
for i in range(2):   # Some log dumping
logging.info("Hello (times %i) from serial job" % (i+1))
```
serial.log:
```bash
2021-04-14 12:31:00,089 root-INFO: Hello (times 1) from serial job
2021-04-14 12:31:00,089 root-INFO: Hello (times 2) from serial job
```
For mpi jobs:
```python
from mpi4py import MPI
from simstop.util.log import initialize_logging
comm = MPI.COMM_WORLD
initialize_logging(mpi=True, filename="mpi.log")
for i in range(2):
logging.warning("Hello (times %i) from mpi job)
```
Resulting mpi.log with 2 MPI processes:
```bash
[rank 0/2] 2021-04-14 …
```
> Simplified logging interface introduced

- .github/workflows/ci.yml
- CMakeLists.txt
- profiling/profiling.cpp
- setup.py
- src/simsgeopp/biot_savart.cpp
- src/simsgeopp/biot_savart.h
- src/simsgeopp/biot_savart_c.cpp
- src/simsgeopp/biot_savart_c.h
- src/simsgeopp/biot_savart_impl.h
- src/simsgeopp/biot_savart_py.cpp
- src/simsgeopp/biot_savart_py.h
- src/simsgeopp/biot_savart_vjp_c.cpp
- src/simsgeopp/biot_savart_vjp_c.h
- src/simsgeopp/biot_savart_vjp_impl.h
- src/simsgeopp/biot_savart_vjp_py.cpp
- src/simsgeopp/biot_savart_vjp_py.h
- src/simsgeopp/python.cpp
- src/simsgeopp/simdhelpers.h
This PR makes two main changes:
- Compile with `-march=native` when compiled locally. Compile with `-march=ivybridge`  when compiled on the CI for our wheels. Ivy Bridge supports avx but is old enough that we can probably rely on this wheel working everywhere.
- If compiled with AVX512F instructions available, then we use a Fast Inverse Square root trick to speed up the computation of `1/||diff||`, since both inverses and square roots are pretty slow on current AVX512 hardware.
> Faster Biot Savart

- .github/workflows/ci.yml
The simsopt CI was failing at the step of compiling SPEC, due to some recent changes in the SPEC repository. This is now fixed, and all tests pass now. Basically the only change in simsopt is that serial HDF5 is used in the CI instead of parallel HDF5.
> Bugfix: CI SPEC compilation

- .github/workflows/ci.yml
- .github/workflows/wheel.yml
- setup.cfg
- src/simsopt/_core/graph_optimizable.py
- src/simsopt/geo/graph_surface.py
- src/simsopt/objectives/graph_functions.py
- src/simsopt/objectives/graph_least_squares.py
- src/simsopt/util/logging.py
- src/simsopt/util/mpi_logger.py
- tests/core/test_graph_dofs.py
- tests/core/test_graph_optimizable.py
- tests/geo/test_graph_surface.py
1. This PR addresses #66 by merging mbkumar/python-mpi-logger into simsopt and removes the optional dependency so that simsopt could be uploaded to pypi. To test run examples/logger_example.py with mpirun and check mpi.log
2. Github actions wheel workflow is modified to upload the wheels to pypi instead of test.pypi.
3. dofs, state type properties that are synonymous with x type properties in Optimizable class definition are removed (Fixes issue #68).
4. DOF class that is not used anywhere removed (Fixes issue #64).
> Cleanup and refactoring

- docs/source/concepts.rst
- docs/source/getting_started.rst
The "Concepts" section in the Simsopt documentation is expanded in order to include references to the different magnetic fields available and the equations solved by the guiding center solver.
Fixes issue #104
> Documentation for the MagneticField class and Guiding Center solver

- examples/1_Simple/minimize_curve_length.py
- src/simsopt/geo/curve.py
adresses some of the concerns raised in #118 
- add equal scaling for 3d plots of curves
- set `closed=False` by default for curves
> more sensible plotting defaults

- docs/source/getting_started.rst
- requirements.txt
- setup.cfg
- src/simsopt/_core/graph_optimizable.py
While pandas is no longer used in graph_optimizable.py, it was still being imported, included as a dependency, and discussed in the documentation. In this PR, these remaining mentions of pandas are removed.
> Remove pandas

- docs/source/concepts.rst
suggesting fix for minor grammar typo in Curves documentation
A simsopt.geo.curve.Curve is modelled as a function 
. A curve object stores a list of 
quadrature points 
and return**s** all information about the curve, at these quadrature points.
> small typo fix

- src/simsopt/geo/surface.py
switch to using a KDTree in the shortest distance computation of `signed_distance_from_surface`
This improves performance from `O(N*M)` where `N` is the number of points on the
surface and `M` is the number of points for which we want to compute the
distance to `O(log(N)*M)`
> Faster signed distance computaton

- src/simsopt/_core/graph_optimizable.py
- tests/core/test_graph_optimizable.py
Sorts the ancestors of an optimizable by name, which makes it a little easier to work across different optimization problems. e.g. when adding extra optimizables in the graph, it's now a bit easier to predict how this changes the dof order, compared to the old DFS order
> sort ancestors by name

- tests/geo/test_qfm.py
- tests/geo/test_surfacehenneberg.py
Due to updates in the CI environment, some tests related to `SurfaceHenneberg` and `QFMSurface` have started failing in the CI in the past week. This PR gets these tests passing again.
> Get tests passing in CI

- examples/stellarator_benchmarks/1DOF_circularCrossSection_varyAxis_targetIota.py
- examples/stellarator_benchmarks/1DOF_circularCrossSection_varyAxis_targetIota_spec.py
- examples/stellarator_benchmarks/7dof.py
- src/simsopt/geo/surfacegarabedian.py
- src/simsopt/geo/surfacerzfourier.py
- tests/geo/test_surface_garabedian.py
- tests/mhd/test_spec.py
In this PR, the `SurfaceRZFourier.to_Garabedian()` function is moved to `SurfaceGarabedian.from_RZFourier()`. The idea is that `SurfaceRZFourier`, as it is the basis for VMEC and SPEC, should not know about "specialty" surface representations like `SurfaceGarabedian` and `SurfaceHenneberg`. Each specialty surface class should handle the conversion to and from `SurfaceRZFourier`, whereas `SurfaceRZFourier` should be as stable as possible, and not have to have any conversion methods added if a new specialty surface class is introduced. `SurfaceHenneberg` already was organized this way, and now `SurfaceGarabedian` is organized this way too.
> Reorganize SurfaceRZFourier->Garabedian conversion

- .github/workflows/ci.yml
- src/simsopt/__init__.py
- src/simsopt/_core/finite_difference.py
- src/simsopt/solve/__init__.py
- src/simsopt/util/__init__.py
- tests/verify_MPI_not_initialized.py
In the master branch of simsopt presently, MPI is initialized whenever any part of simsopt is imported, even just `import simsopt`. This is a problem because some HPC systems, such as Cobra and Raven at IPP, only allow MPI to be initialized when programs are submitted through slurm, not on login nodes. This means simsopt is not presently usable on the login nodes even for non-computationally-expensive scripts. This might also be frustrating for new users, if they try `import simsopt` on a login node and it crashes with an MPI error. This PR fixes this issue by modifying some imports so that MPI is only initialized when it is really necessary, such as for the `MpiPartition` or `Vmec` classes. A test was also added to the CI to verify that `import simsopt` and importing a surface class do …
> Only initialize MPI if necessary

- src/simsopt/_core/finite_difference.py
- src/simsopt/_core/graph_optimizable.py
- src/simsopt/field/boozermagneticfield.py
- src/simsopt/mhd/__init__.py
- src/simsopt/mhd/boozer.py
- src/simsopt/mhd/spec.py
- src/simsopt/mhd/vmec.py
This PR minimizes the number of warning statements outputted to the screen, mainly import warnings. Import warnings are converted to debug log statements. And miscellaneous print statements are converted to debug statements.
> Minimize warnings output to screen

- src/simsopt/field/boozermagneticfield.py
I fixed one typo on the following line 
https://github.com/hiddenSymmetries/simsopt/blob/e716442b8cf81885675402e66cb28802cea6d8a3/src/simsopt/field/boozermagneticfield.py#L530
> BoozerRadialInterpolant fix

- docs/source/concepts.rst
- src/simsopt/geo/surface.py
- src/simsopt/geo/surfacegarabedian.py
- src/simsopt/geo/surfacehenneberg.py
- src/simsopt/geo/surfacerzfourier.py
- src/simsopt/geo/surfacexyzfourier.py
- src/simsopt/geo/surfacexyztensorfourier.py
- tests/geo/test_surface.py
Presently, surface integrals are inaccurate when `range="half period"`. After the change in this PR, integrals are now spectrally accurate (as they have been for `range="full torus"` and `field period`).
Addresses #174 .
> Surfaces: shift phi grid by half the grid spacing when range='half period'

- docs/source/simsopt.rst
- docs/source/simsoptpp.rst
This PR makes sure that the C++ documentation shows up and is linked properly to the python documentation. For example, when looking at `simsopt.field.biotsavart.BiotSavart`, there is now a link to `simsoptpp.BiotSavart`
> better cpp documentation linking

- ci/Dockerfile.ubuntu
This PR modifies Dockerfile.ubuntu as a preliminary step to get the docker imagefile work with shifter at NERSC. In place of openmpi, mpich is used to take advantage of mpich's ABI compatibility.
Specifically, the docker container build is modified to build mpich and scalapack manually in place of libopenmpi-dev, openmpi-bin, and libscalapack-dev installed with apt-get. libboost-all-dev is also not installed to prevent mpi libraries installed as dependencies by apt-get.
> Use mpich for docker container

- conda.recipe/meta.yaml
- docs/source/installation.rst
- requirements.txt
- setup.cfg
Trying to tidy up a few things related to requirements.
- Some items and version numbers synchronized between `requirements.txt`, `setup.cfg`, and `conda.recipe/meta.yaml`.
- Added pyevtk to requirements and conda `meta.yml` since it is needed for the `stage_two_optimization.py` example.
- The list of required packages in the ReadTheDocs installation page was removed, so we don't have to keep it synchronized with the lists in `requirements.txt` and `setup.cfg`. It was already a bit out of date.
- Added optional `[DOCS]` requirements in `setup.cfg` for building the docs.
> Tidying up requirements

- src/simsopt/geo/surfacehenneberg.py
- src/simsopt/geo/surfacerzfourier.py
- tests/geo/test_surface_rzfourier.py
- tests/geo/test_surfacehenneberg.py
Fixed a few issues with the graph framework dofs getting out of sync with arrays owned by Surface objects
> Fix: graph framework dofs out of sync

- src/simsopt/_core/graph_optimizable.py
- src/simsopt/geo/curvehelical.py
- src/simsopt/geo/curvexyzfourier.py
This PR fixes the CI failures that have been happening the past few days. The cause is that Jax removed the command `index_add` in a release a few days ago:
https://jax.readthedocs.io/en/latest/changelog.html#jax-0-3-2-march-16-2022
So in this PR I've replaced `index_add` with the recommended alternative, `.at[idx].add()`.
> Removed deprecated jax commands

- .github/workflows/ci.yml
- setup.py
- src/simsoptpp/tracing.cpp
I noticed that one of the tests triggered this assert, when running the test suite on a Debug build of simsoptpp. It never failed on CI because asserts are not active when building in Release mode.
I checked with @ejpaul and she confirmed that this can go.
> Remove assert in tracing.cpp

- src/simsopt/_core/derivative.py
- src/simsopt/_core/graph_optimizable.py
- src/simsopt/geo/curve.py
- src/simsopt/objectives/fluxobjective.py
- src/simsoptpp/python.cpp
- tests/core/test_derivative.py
- tests/geo/test_curve.py
Motivated by some interesting conversations with @zhucaoxiang about improving performance in SIMSOPT and FOCUS, I have been doing some digging into bottlenecks when doing deterministic coil optimization.
When running on multiple cores, we essentially run into [Amdahl's law](https://en.wikipedia.org/wiki/Amdahl%27s_law): eventually the serial aspects of the code start becoming the bottleneck, and even though our BiotSavart code scales nicely in parallel, the overall scalability is poor.
Two low hanging fruits that I noticed are:
- The computation of the surface integral `∫(B·n)²ds` is now done in C++ (to enable OpenMP parallelization)
- since our derivative objects are essentially dictionaries that use Optimizable objects as keys, the `__hash__` function is called very very frequently in …
> Small performance tweaks

- CMakeLists.txt
- docs/source/example_coils.rst
- docs/source/geo.rst
- examples/2_Intermediate/stage_two_optimization.py
- examples/2_Intermediate/stage_two_optimization_stochastic.py
- src/simsopt/geo/curveobjectives.py
- src/simsoptpp/python.cpp
- src/simsoptpp/python_distance.cpp
- tests/geo/test_curve_objectives.py
- tests/geo/test_curveperturbed.py
Summary
- introduced `CurveSurfaceDistance` objective to enforce minimum distance constraints between the coils and a surface
- renamed `MinimumDistance` to `CurveCurveDistance`
- exploit symmetries to avoid computing redundant distances
- added C++ routines that return which pairs of curves are within a certain threshold of each other and which curves are within a threshold of a surface.
The idea behind the last point is:
- Assume we want to compare pointcloud A and B.
- We create a uniform grid of size `threshold`.
- Loop over points in cloud A, mark all cells that have a point in it (blue in the image).
- Loop over points in cloud B, mark all cells that have a point in it (green) and also all neighbouring cells around it (red).
- Check whether the intersection `(green ∪ red) ∩ blue` …
> Curve-Curve distance improvements and introduction of Curve-Surface distance

- src/simsopt/mhd/vmec.py
In stage one optimization, if there are multiple mpi processes per worker group, there can be a problem where proc 0 deletes a wout file before other procs have read it. In this PR an MPI barrier is added to avoid this condition.
> mpi barrier to avoid wout not found error

- examples/2_Intermediate/stage_two_optimization.py
- src/simsopt/_core/optimizable.py
- tests/core/test_derivative.py
Often we use a weight in front of a penalty, then solve and optimization problem, and then we want to adjust the weight and solve the problem again.
With this PR one can now write
```
J1 = SomeObjective()
J2 = SomePenalty()
alpha = Weight(1e1)
J = J1 + alpha * J2
minimize(J,...)
alpha *= 100
minimize(J, ...)
```
> Add a Weight object that encapsules a scalar

- docs/source/example_coils.rst
- docs/source/example_quasisymmetry.rst
- docs/source/example_vmec_only.rst
- docs/source/fields.rst
- docs/source/geo.rst
- docs/source/index.rst
- docs/source/optimizable.rst
- docs/source/overview.rst
- docs/source/tracing.rst
- examples/1_Simple/stage_two_optimization_minimal.py
- examples/run_serial_examples
- src/simsopt/configs/zoo.py
- src/simsopt/field/__init__.py
- src/simsopt/field/magneticfield.py
- src/simsopt/geo/__init__.py
- src/simsopt/geo/curve.py
- src/simsopt/geo/surface.py
This PR includes some improvements to the documentation:
- Fixed some links to the API docs that were not working in the docs after merging #239.
- Simplified more of the sub-submodule imports to submodule imports in the docs.
- In the coil optimization tutorial, the minimal example was simplified, and a new section was added to list the many available regularization terms.
- `stage_two_optimization.py` was split into a simpler minimal version and a version with all the regularization terms.
> Improvements to documentation

- .github/workflows/wheel.yml
With this PR, the source distribution is built in PEP-517 compliant manner. This addresses  the issue faced by Caoxiang's student in installing simsopt from source. I tested it by installing simsopt from the newly built source distribution.
> Update sdist build

- tests/mhd/test_vmec_diagnostics.py
On my new laptop one of the tests was failing since 0.0 != 1e-16. This is fixed in this pull request.
> Fixed one vmec_fieldlines test that was failing

- docs/source/publications.rst
- src/simsopt/geo/surfacerzfourier.py
For high Fourier resolution, e.g. mpol=ntor=50, the function `SurfaceRZFourier.from_vmec_input()` can take several seconds. This small change makes it substantially faster.
> Updated SurfaceRZFourier.from_vmec_input() to be faster.

- .github/workflows/wheel.yml
At the last release, [the wheel CI](https://github.com/hiddenSymmetries/simsopt/actions/runs/3210554344) gave this warning:
(which I think is unrelated to the CI failure). This PR addresses the warning.
> Updated pypa/gh-action-pypi-publish from master to release/v1

- src/simsopt/mhd/vmec_diagnostics.py
- tests/mhd/test_vmec_diagnostics.py
In this pull request, some of the calculations inside `vmec_fieldlines()` are separated out into a new function `vmec_compute_geometry()`. This new function can be called to get geometric quantities of interest on grids that are not grids along a field line. In particular, you can now get the geometric quantities on a tensor product grid in (theta, phi). The main purpose of `vmec_fieldlines()` is now just the root-finding problem (solving for theta_vmec along a field line), with all the other geometry calculations delegated to `vmec_compute_geometry()`. Users of `vmec_fieldlines()` will not notice any changes - all results of that function are identical to before.
> fieldlines refactor

- tests/geo/test_qfm.py
The test `test_qfm_surface_optimization_convergence` has been occasionally failing in the CI. The tests were failing by only a tiny bit- there were differences between target and achieved values of 2e-5, larger than the threshold difference of 1e-5. In this PR I raise the thresholds to 3e5, and also fix the random seed so the test is more reproducible.
> Fix failing test in CI, test_qfm_surface_optimization_convergence

- .github/workflows/ci.yml
- .github/workflows/conda.yml
- .github/workflows/docker.yml
- .github/workflows/extensive_ci.yml
- .github/workflows/linting.yml
- .github/workflows/singularity.yml
- .github/workflows/wheel.yml
The github actions we use are dependent on node.js v12, which has been deprecated and going out of service sometime in 2023. In this PR, the actions are updated to use node.js v16, the current default.
> Update Github Actions Versions

- .github/workflows/docker.yml
- .github/workflows/wheel.yml
Mac wheel building is updated to use `cibuildwheel`. `cibuildwheel` version is upgraded to the latest. Support for arm64 arch added for macOS.
> Updated workflows

- src/simsoptpp/python_surfaces.cpp
- tests/README.md
When implementing SurfaceNewQuadPoints class, I noticed that some of the pybind11 code is not canonical. Minor change, but properly captures the underlying inheritance and polymorphism.
> Pybind11 changes

- src/simsoptpp/regular_grid_interpolant_3d.h
There is a bug in simd padding in RegularGridInterpolant3D. When the size is the multiple of simdcount, spurious padding bytes are added.
> Bug fix for padding in RegularGridInterpolant3D

- examples/2_Intermediate/winding_volume_axi.py
- src/simsopt/geo/winding_volume_grid.py
This PR adds some routines to display the voxels as voxels rather than points. Two files are saved, one with only the base voxels (not applying stellarator symmetry or nfp symmetry), and the other with all voxels (exploiting the symmetries.) Examples:
In Paraview, I like setting "Representation" to "Surface with edges".
The boundaries of each voxel are defined by the max and min of the quadrature points. Therefore the 2nd figure shows gaps between each half period due to the issue we just discussed by email.
Also, a vtk file with the quadrature points is now saved.
For expediency while developing this, for now the voxel data are saved before the solve rather than after, so J data isn't included. But you could add calls to the new`_voxels_to_vtk()` function in `to_vtk_after_solve()` to add …
> Visualize voxels

- tests/field/test_magneticfields.py
- tests/geo/test_surface_xyzfourier.py
- tests/mhd/test_virtual_casing.py
This PR adds some minor fixes to tests to make them optional and definitive.
> Minor fixes in some tests

- CMakeLists.txt
Getting CMake to recognize OpenMP on Mac is very hard. The homebrew is releasing only ARM64 arch for M1 and CMake insists on universal binary. To circumvent this, we can leverage conda toolchain to find OpenMP. 
1. Install llvm-openmp from conda
`conda install -c conda-forge llvm-openmp`
2. Install dependencies from conda
3. Use no-build-isolation to find openmp from conda when installing simsopt locally.
`pip install --no-build-isloation .`  
In this PR, CMakeLists.txt is updated to use headers and libraries installed in the conda virtual environment.
Edit: PR #293  is also included in this PR.
> Mac openmp fix

- docs/source/example_coils.rst
- examples/1_Simple/stage_two_optimization_minimal.py
- examples/2_Intermediate/stage_two_optimization.py
- examples/2_Intermediate/stage_two_optimization_finite_beta.py
- examples/2_Intermediate/stage_two_optimization_stochastic.py
- examples/3_Advanced/stage_two_optimization_finitebuild.py
- src/simsopt/objectives/utilities.py
Yikes, discussing with Antoine Cerfon just now, we realized there was an important error with all the simsopt stage-2 coil optimization examples and documentation. All the `QuadraticPenalty` terms were missing the `"max"` argument. The default for `QuadraticPenalty` was `"min"`, meaning that coil length and mean-squared-curvature were penalized only if they were below the target rather than above. I don't know how this error made it in. This problem is fixed in the examples and tutorial in this PR.
In this PR the default for `QuadraticPenalty` is also changed from `"min"` to `"identity"`. We only ever use `"max"` or `"identity"` in the examples, never `"min"`. Also `"identity"` seems like a safer and more intuitive default.
> Bug in coil examples and docs: missing "max" argument

- src/simsopt/geo/surfacerzfourier.py
- tests/geo/test_surface_rzfourier.py
This PR allows users to generate a SurfaceRZFourier directly from a pyQSC instance (a Qsc class).
It helps users perform stage 1 and stage 2 optimizations involving near-axis expansions, either as initial conditions or not.
> PR: Added a surface.from_pyQSC method and tests

- .github/workflows/conda.yml
- CMakeLists.txt
- conda.recipe/conda_build_config.yaml
- config.h.in
- setup.cfg
- src/simsoptpp/biot_savart_impl.h
This PR fixes two issues with conda build.
1. conda build on Mac is failing due to boost using some classes deprecated in C++17. Some compilers removed those features, but some didn't. So the build is working only on Linux. This PR fixes the C++17 incompatibility with boost.  
2. Adds simsopt conda packages for python v3.10. Had to bump minimal numpy version to 1.21 which is the first numpy version to support python 3.10.
> conda build fixes

- CMakeLists.txt
- docs/source/example_coils.rst
- examples/3_Advanced/single_stage_optimization.py
- examples/3_Advanced/single_stage_optimization_finite_beta.py
- src/simsopt/objectives/fluxobjective.py
- src/simsoptpp/integral_BdotN.cpp
- src/simsoptpp/integral_BdotN.h
- src/simsoptpp/python.cpp
- tests/objectives/test_fluxobjective.py
*  The PR `rj/single_stage_PR` eliminates the original definition of `SquaredFlux`. I think we should keep this original definition as an option so it doesn't break scripts of other users, and since it may be useful in some circumstances. Therefore in this PR, in `SquaredFlux` I replaced the boolean `local` argument with a `definitions` argument of string type that can take 3 options. These 3 options correspond to the original definition of `SquaredFlux` plus the 2 new definitions in `rj/single_stage_PR`.
* All the available definitions for `SquaredFlux` are now tested, and the derivatives are tested.
* The available definitions of `SquaredFlux` are now documented with displayed equations.
* To simplify `python.cpp`, the `integral_BdotN` function was separated out of `python.cpp` into a …
> options for SquaredFlux definition

- examples/3_Advanced/single_stage_optimization_finite_beta.py
- src/simsopt/_core/finite_difference.py
- src/simsopt/_core/optimizable.py
- tests/core/test_finite_difference.py
- tests/core/test_optimizable.py
This is yet another possible refactoring of the single-stage example in #301 suggested by @mbkumar, as an alternative to #317. In this approach, `MPIFiniteDifference` broadcasts `full_x` instead of just the free `x`, so there is no extra data that needs to be broadcast. The coil dofs are fixed during the finite-differencing, then un-fixed to update the coil dofs and compute their gradient analytically, then fixed again for the next finite-differencing, etc. Even though the coil dofs are fixed during the finite differencing, they are still part of `full_x`, so they get broadcast.
To get this working, a few functions were added to `Optimizable`: a setter for `full_x` (copied from @mbkumar 's commit to #317), and `full_fix()` and `full_unfix()` to set the free/fixed property for the full …
> Yet another single-stage refactor

- docs/source/fields.rst
- src/simsopt/field/magneticfieldclasses.py
- tests/field/test_magneticfields.py
This PR introduces the mirror machine model from https://arxiv.org/abs/2305.06372
It expands the set of magnetic field models available to SIMSOPT to include a magnetic mirror model for fusion applications. The default input parameters follow the ones used to model WHAM (https://wippl.wisc.edu/wisconsin-hts-axisymmetric-mirror/)
> New magnetic field class - mirror machine

- .coveragerc
- .github/workflows/ci.yml
- .github/workflows/extensive_ci.yml
- .github/workflows/wheel.yml
Python 3.7 is reaching its end of life in ten days.  I am removing 3.7 and adding 3.10 to the extensive CI.
> Removing python 3.7 in CI due to its EOL in a week

- CMakeLists.txt
> fix #278: tracing.hpp does not find boost

- .github/workflows/docker.yml
After SPEC became open source, this token is not needed anymore.
> SPEC access token removed from docker

- src/simsopt/geo/permanent_magnet_grid.py
- src/simsopt/mhd/vmec.py
- src/simsoptpp/dipole_field.cpp
- src/simsoptpp/dipole_field.h
- src/simsoptpp/python.cpp
- tests/geo/test_pm_grid.py
This branch fixes an issue with the grid generation for permanent magnets, particularly for uniform cylindrical grids, pointed out by @MigMadeira. Basically, the magnets are initialized on a uniform grid (cartesian, cylindrical, or simple toroidal), and then magnets that do not lie between an inner and outer toroidal surface are eliminated by a ray-tracing routine. Some of the magnets near pi and 2pi  were incorrectly eliminated or incorrectly kept around. I think this is because of not being careful that the inner, outer, and plasma surfaces all had the same toroidal angle range between [0, 2pi], and that the ray tracing knew that 0 and 360 were the same angle. 
Part of this issue is that, for historical reasons (bad coding), I had a separate ray tracing routine for both the cartesian …
> Cylindrical magnets grid fix

- src/simsopt/geo/curve.py
- src/simsopt/mhd/vmec.py
- tests/mhd/test_vmec.py
This PR addresses an issue we noticed when doing free-boundary vmec calculations following stage-2 coil optimization. The function `create_equally_spaced_curves()` has a sign convention associated with which way the curve parameter increases. In other words, does a positive current correspond to current going up or down through the plasma's donut hole? We need to be particularly careful about this sign in finite-beta stage-2 optimizations (see `examples/2_Intermediate/stage_two_optimization_finite_beta.py`), where the sign of the coil currents is set by `Vmec.external_current()`, and Bnormal from virtual casing must have the proper sign relation to B from the coils. In the master branch, the signs are not correct, such that when you run free-boundary vmec from the optimized coils, there …
> Flip orientation in create_equally_spaced_curves() to fix free-boundary

- src/simsopt/mhd/vmec_diagnostics.py
... no idea why this still works as-is (`js` is not defined in the scope), but Python somehow magically seems to find the correct value. Anyway, I think one should use the (intended?) `jradius` here.
> [FIX] theta_vmec computation in vmec_fieldlines

- src/simsopt/field/tracing.py
The routine plot_poincare_data had as argument 'aspect' (by default set to 'equal') but actually never used it, which meant that the poincare plots were produced without the 'equal aspect ratio'. This is just a quick fix so that the function actually sets the aspect ratio as desired.
> added use of axis aspect ratio argument when plotting poincare sections

- src/simsopt/mhd/virtual_casing.py
This PR allows the user to plot the squared flux in the full torus range when using the virtual-casing package instead of only plotting half or a single field period.
> Extend virtual casing to full torus

- tests/field/test_biotsavart.py
Caught this bug when doing the linter fixes.
> bug fix in test_biotsavart.py

- tests/geo/test_strainopt.py
This PR is in response to  #371. Assert statements have now been included in the unit tests for the LPTorsionalStrainPenalty and LPBinormalCurvatureStrainPenalty.
> Fix to unittest.

- src/simsopt/mhd/vmec.py
With this PR, `pres_scale` is added as an optimizable d.o.f. of Vmec objects, allowing the pressure profile to be scaled up and down.
Previously, Vmec objects also had some optimizable dofs that really should not ever be varied in an optimization: `delt`, `tcon0`, and `gamma`. These parameters are now removed as optimizable dofs.
> Clean up dofs of Vmec objects

- src/simsopt/field/mgrid.py
- src/simsopt/mhd/virtual_casing.py
[This change to scipy's netcdf module](https://github.com/scipy/scipy/commit/1bd1607fdbb5d762a7ff7bc851074cb38f829d1c) in scipy v1.12 causes simsopt's netcdf-writing functions to fail when setting scalar (i.e. 0D) values. I'm not sure why that change was made to scipy because `numpy.ndarray.itemset` does not appear to be deprecated. Anyhow, this pull request makes simsopt's netcdf routines work with scipy 1.12, while also working with earlier scipy versions. No changes to the required versions of numpy or scipy for simsopt are needed.
> Fix error with netcdf scalars in scipy v1.12

- src/simsopt/geo/__init__.py
In jax 0.4.25, released last month, `jax.config.config` was [deprecated](https://github.com/google/jax/blob/main/CHANGELOG.md#jax-0425-feb-26-2024), which causes simsopt to break with this jax version. In particular the CI is failing. This PR is a fix. The change works with older jax versions too - simsopt was already using the new syntax `import jax; jax.config.update(...)` in another location (`geo/jit.py`.)
> Tweak for compatibility with jax 0.4.25

- .github/workflows/extensive_test.yml
- src/simsopt/geo/surface.py
- tests/geo/test_surface.py
- tests/geo/test_surface_taylor.py
This PR introduces a surface self-intersection test, and second derivatives of the surface aspect ratio with respect to the surface degrees of freedom.
The algorithm that checks for surface self-intersection first computes a surface cross section at a given cylindrical angle phi.  Then, approximating the cross section as a piecewise linear polyline, the Bentley-Ottmann algorithm is used to check if any line segments overlap one another.
The second derivatives of surface aspect ratio are useful if being used as a surface label in the BoozerLS algorithm.
> added surface self-intersection test as well as second derivatives of surface aspect ratio

- pyproject.toml
This PR attempts to fix the problem described in issue #405, where `mayavi` is not being installed correctly during `test.yml`.   It seems like the installation problem has been documented here:
https://github.com/enthought/mayavi/issues/1219
where the upshot is to install from source.
In branch `ag/fix_issue_405`, I install `mayavi` from source on the runner without issues:
https://github.com/hiddenSymmetries/simsopt/compare/master...ag/fix_issue_405
but runtime errors associated to `mayavi` appear now instead (rather than compile time errors as previously)
https://github.com/hiddenSymmetries/simsopt/actions/runs/8793008167/job/24130188871
and I have not yet been able to resolve the runtime errors.
I think the easiest path forward is to remove mayavi from the optional-dependencies in …
> fix for issue #405

- src/simsopt/geo/surfacerzfourier.py
- tests/geo/test_surface_rzfourier.py
This PR adds a convenience function to make `SurfaceRZFourier` surfaces that are rotating ellipses.
I decided not to make this a `@classmethod` so users have the option to specify either `quadpoints_theta` and `quadpoints_phi`, or specify `range`, `nphi`, and `ntheta` with `@classmethod from_nphi_ntheta()`.
> Rotating ellipse surface

- docs/source/simsopt.geo.rst
- src/simsopt/geo/__init__.py
- src/simsopt/geo/curvexyzfouriersymmetries.py
- src/simsopt/geo/curvexyzhelical.py
- tests/geo/test_curve.py
This pull request introduces a new helical curve representation called `CurveXYZHelical`.  This curve is different from `CurveXYZFourier` because it can have discrete rotational symmetry.  It can also be stellarator symmetric, or not.
We currently support a helical curve representation `CurveHelical`, but this curve is restricted to lie on a torus.  The new  `CurveXYZHelical` is not restricted to lie on a torus, and can represent curves like the one below.  Viewing from above, the  `CurveXYZHelical` appears to lie on a torus
but profile view reveals that it clearly does not:
When `CurveXYZHelical` is stellarator symmetric, then necessarily the curve must pass through the point `(x0, 0, 0)`.  If you do not want this, then the user can apply stellarator symmetry to a non-stellarator …
> CurveXYZFourierSymmetries

- src/simsopt/solve/mpi.py
- src/simsopt/solve/serial.py
- tests/mhd/test_integrated_mpi.py
- tests/solve/test_least_squares.py
When running optimizations for least-squares problems, the vector of residuals is saved at each iteration. For objectives like quasisymmetry with lots of residuals, this file can get quite large. So this PR makes the residuals file optional.
> Make residuals file optional

- src/simsopt/mhd/vmec_diagnostics.py
Adds support for stellarator non-symmetric configurations in vmec_splines. A notable example of such a configuration is ITER, where the lower-null divertor breaks stellarator symmetry. 
For stellarator symmetric configuration, the additional outputs are all zero.
> Stellarator non-symmetric configurations in vmec_splines

- src/simsopt/geo/boozersurface.py
- tests/geo/surface_test_helpers.py
- tests/geo/test_boozersurface.py
The user has the option to optimize coils using the BoozerLS algorithm while fixing the constant `G` to its theoretical value in vacuum field, i.e., providing `G=None` to boozer_surface.run_code().  When computing the gradient of an objective function that depends on such a BoozerLS surface (with `G=None`), the gradient formulas assume that coil currents are fixed.  In order to avoid confusion, I have added an assert to prevent the algorithm from proceeding if the currents are unfixed, as the computed gradient would be incorrect.
> adding an assert statement

- pyproject.toml
This PR adds python-version specific dependencies to address numpy compatibility with v1.x and v2.x.
There is one spec test failing in 3.8. Could that be due to numpy 2.0 and numpy 1.x differences?
@smiet, can you please invetigate?
> Fix for python 3.8 and numpy dependency

- src/simsopt/mhd/spec.py
Should fix the sporadic failure in the CI #357
The issue: f90wrap uses getter and setters to access the F90wrapped FORTRAN arrays, and the logic is as follows: 
```Python
handle = get_specific_array_handle(stuff)  #pointer to the array
if handle in self._arrays #dict with arrays and handles:
return self._arrays[handle]
else:
array = get_array_in_complicated_f90wrapway(stuff)
self._arrays[handle]=array
return array
```
Now for the race condition: If spec has run before, and the array has been accessed before (put in cache), and *by happenstance* the handle remains the same, python will return the cached array, and not access the FORTRAN memory. 
The handle is basically the pointer to the array, cast as an int. It is unlikely to be exactly the same EXCEPT when a conveniently shaped hole has …
> clear spec cache to avoid sporadic mismatch

- src/simsopt/mhd/boozer.py
> Fix logging error in boozer.py to address #435

- src/simsopt/mhd/boozer.py
Currently, only MPI _leaders_ run the majority of the `run` method of the BoozXform. This would be fine, except there is no use of MPI broadcast to send the all results of the run to the MPI _workers_. For example, on line 168 the MPI leaders will set `self.bx.asym = bool(wout.lasym)` (a boolean for stellarator symmetry), whereas the MPI workers will still be stuck with the default value of `self.bx.asym` since they never run this line. This can cause downstream problems in codes that depend on these properties, such as the `BoozerRadialInterpolant` class.
This PR proposes to allow _all_ MPI cores to run the entire function, rather than just the leaders. 
**Downsides**
- Our cores are technically doing more work. Nonetheless, this should not affect run time.
**Upsides**
- Ensures …
> Removed separation of MPI ranks during boozXform

- .github/workflows/extensive_test.yml
- .github/workflows/tests.yml
- ci/Dockerfile.ubuntu
- ci/singularity.def
f90wrap does not need to follow Caoxiang's branch anymore as his fix has been merged into upstream. Tests were still following this branch. 
Pyoculus is not automatically uploaded to pypi, so to facilitate getting changes from master to simsopt, this is now installed directly from master.
> install pyoculus from git and f90wrap from pypi

- src/simsopt/solve/mpi.py
- tests/solve/test_mpi.py
When vmec fails to converge on the first function evaluation of an optimization, MPI proc 0 exits with an uncaught exception while other procs do not, causing the code to hang due to the MPI communication getting out of sync. This can result is wasted time on the cluster, as jobs don't exit cleanly and keep occupying nodes even though they are not actually working on an optimization. This PR fixes this issue, and the new test here provides coverage for this issue.
> Fix MPI issue with vmec crashes in 1st evaluation

- src/simsopt/mhd/spec.py
There was a typo in the spec module, and the **non-stellerator symmetric terms** were being set if the `freebound` flag was false, when it should have been the `stellsym` flag.
I think the fix is pretty self explanatory ;)
> Bugfix for SPEC non-stellerator symmetric case

- src/simsopt/_core/optimizable.py
- tests/core/test_dofs.py
NINF was deprecated and should be replaced with -np.inf
> np.NINF to -np.inf for np2.0 compatibility

- docs/source/example_islands.rst
- docs/source/example_quasisymmetry.rst
Two examples in the documentation folder weren't working with the current simsopt version, because a `.J` was missing
> (Minor Fix) two broken examples in docs

- .github/workflows/wheel.yml
The wheel workflow recently [stopped working](https://github.com/hiddenSymmetries/simsopt/actions/runs/13074530769). With this PR it is working again. I've mainly followed [this example from cibuildwheel](https://github.com/pypa/cibuildwheel/blob/main/examples/github-deploy.yml). 
The workflow takes longer to run now because wheels are built for more platforms now, in particular `musllinux` and linux `i686` (in addition to `manylinux` and `x86_64`).  This is done by default in the cibuildwheel example workflow that I copied, and the wheels were built without error, so I kept these platforms. We could potentially remove these cases if nobody would use them and the longer workflow runtime is a problem.
> Fix wheel workflow

- src/simsopt/solve/permanent_magnet_optimization.py
I noticed that the `relax_and_split()` method in the permanent magnet optimization tools was `.pop()'-ing keys such as `nu` and the regularization terms out of `kwargs`, even though these should actually be passed to the convex MwPGP algorithm in the code block:
```
algorithm_history, _, _, m = convex_step(
A_obj=pm_opt.A_obj,
b_obj=pm_opt.b_obj,
ATb=ATb,
m_proxy=np.ascontiguousarray(m_proxy.reshape(pm_opt.ndipoles, 3)),
m0=np.ascontiguousarray(m.reshape(pm_opt.ndipoles, 3)),  # note updated m is new guess
m_maxima=mmax,
**kwargs
)
```
This causes a bug where if you optimize with `relax_and_split()`, the default value of nu = 1e100 is used since this key has been removed from the kwargs dict when it is passed on to the convex MwPGP method. This pull request changes it to a `get()` method …
> Fix relax_and_split kwargs dict passing

- .gitmodules
- CMakeLists.txt
- ci/Dockerfile.ubuntu
The way pybind11 is sourced changed long time ago. Instead of using a git submodule, the pybind11 package is downloaded and installed using python's build framework. The orphaned pybind11 submodule is removed.
> Unused pybind11 module removed

- .github/workflows/wheel.yml
Currently wheels are being built for i68c and musllinux architectures. Not worth building wheels not going to be used.
> Stop building wheels for non-HPC architectures

- src/simsopt/geo/surface.py
This bug-fix is part of Simsopt fix-it week 2025.
It updates the documentation of simsopt.geo.Surface.cross_section.
I assumed that cross_section is a float in [m²] and ran no tests because this only updates one documentation string.
> updates cross_section documentation

- src/simsopt/geo/curverzfourier.py
- tests/geo/test_curve.py
This bug-fix is part of **Simsopt fix-it week 2025**. 
It addresses a bug in the class `CurveRZFourier`. According to the documentation, the degrees of freedom (dofs) should be listed as 
```[r_{c,0}, \cdots, r_{c,\text{order}}, r_{s,1}, \cdots, r_{s,\text{order}}, z_{c,0},....]```
if `stellsym` is false, and
```[r_{c,0},...,r_{c,order},z_{s,1},...,z_{s,order}]```
if stellsym is True. 
However, a dof naming function did not exist so the dofs were being stored as 
```[x0, x1, /cdots, x{num_dofs]```.
This pull request fixes this issue by adding a `_make_names` function, which names the dofs according to the documentation. It is modeled after the existing function used to names the dofs in `CurveXYZFourier`. Its functionality has been tested for both stellarator symmetric and non-stellarator …
> Bug fix for adding dof names in CurveRZFourier Class

- docs/source/cpp.rst
This PR is a proposed resolution to issue #482.
The previous version of the instructions for recompiling ``simsoptpp`` presumed that the shared object file for simsoptpp used by Python would be stored in the ``src`` directory. However, this is no longer the case in the latest versions, and the instructions in their original form would no achieve the desired outcome.
This commit updates the instructions to be agnostic to the location of the shared object file used by Python, using the Python command ``print(simsoptpp.__file__)`` to directly look up the correct location.
> Resolve issue 482: update instructions for recompiling simsoptpp

- src/simsopt/geo/curvehelical.py
- tests/field/test_coil.py
- tests/field/test_fieldline.py
- tests/field/test_magneticfields.py
- tests/geo/test_curve.py
- tests/geo/test_curve_helical.py
This PR addresses several issues with `CurveHelical`:
* Previously `order` had been defined so the maximum mode number was `order - 1`, inconsistent with the rest of simsopt where the maximum mode number is `order` (inclusive). With this PR, the maximum mode number is changed to be `order` for consistency.
* The dofs had included a mode amplitude for the k=0 term in the sine terms, which is meaningless. This dof is now removed.
* There wasn't much description in the docstring. More detail is added here.
* Some of the curve parameter names weren't consistent with the Cary-Hanson and Hanson-Cary papers, which are a major motivation for this curve type. E.g. n0 instead of m, r0 instead of r. In this PR, these parameters are renamed to match the papers.
* The dofs previously used the default …
> Improve CurveHelical

- .readthedocs.yaml
- docs/README.md
- docs/requirements.txt
- docs/source/conf.py
- docs/source/cpp.rst
- docs/source/link-roles.py
Created the framework to point the code links in the documentation on the ReadTheDocs website to the simsopt GitHub repo. 
I updated the links only in two places in https://simsopt.readthedocs.io/mbk-gh_links/cpp.html. 
One drawback is branch names are not properly generated. The code to generate the branch names is working properly on my laptop and GH runner, but not on RTD runner. Since we point to only master and versioned releases in the docs, this should be OK. I didn't check the links generated for the releases yet. We can only do that after merging the PR and creating a new version of simsopt.
The README in the docs folder contains info on how to add links to GH code.
> [skip ci] Code links in the ReadTheDocs pointing to GitHub

- src/simsoptpp/python_tracing.cpp
- src/simsoptpp/tracing.h
- tests/field/test_particle.py
I've sometimes wanted to follow field lines for a number of toroidal transits that is not an integer, for field lines that are periodic in the (R,Z) plane after a number of field periods different from nfp. This isn't possible now with ToroidalTransitStoppingCriterion because the max_transits argument has type int. In this tiny PR I just change the type to double to enable this functionality.
Users who have been using the argument type `int` should notice no differences. For test coverage, I just randomly picked two of the tests that used ToroidalTransitStoppingCriterion and changed the argument from int to float. In other tests the argument remains an int, so both types are covered.
> ToroidalTransitStoppingCriterion: changed max_transits to double

- src/simsopt/field/tracing.py
- tests/field/test_fieldline.py
This PR updates the function `plot_poincare_data` to use the new angle convention for `Surface.cross_section` if a user supplies a Surface class instance as an optional argument. Also modifies the unit test of plot_poincare_data to include surface cross-sections in the plot; hopefully this increases the test coverage a bit.
> Update plot_poincare_data to use new cross_section angle convention

- .github/workflows/conda.yml
- .github/workflows/docker.yml
- .github/workflows/docs_test.yml
- .github/workflows/extensive_test.yml
- .github/workflows/non_simd_tests.yml
- .github/workflows/singularity.yml
- .github/workflows/tests.yml
- .github/workflows/wheel.yml
- conda.recipe/meta.yaml
I noticed that when we push fixes in quick succession, the workflows for previous fixes keep on running. This slows down the testing quite a bit. Earlier, I was manually canceling the workflows associated with prior pushes. Now the workflows are automatically canceled, and the resources are released for the new workflows.
Tested and found it working.
> Cancel in-progress workflows if a new code is pushed

- src/simsopt/geo/surface.py
- tests/geo/test_surface.py
This PR makes two fixes to the `Surface.cross_section` function. 
1. The documentation was not compiling correctly, which made it difficult to understand what the arguments and returns were. The documentation has now been corrected. See attached.
2. The `thetas` argument can be one of `int, Array, None`.  However, when an array or list was passed in, an error would be thrown. The error was arising because of improper validation of inputs: there was no handling for the case when `thetas` is an array. In this PR, we correct the validation of the inputs to allow for `thetas` to be an array, as the documentation states it can be.
**Changes**
- Small changes have been made to the `cross_section` method and documentation.
- A basic unit test has been added to check that an array can be used as …
> Bug in Surface Cross Section arguments

- examples/2_Intermediate/boozerQA.py
- src/simsopt/field/mgrid.py
- src/simsopt/geo/surfacegarabedian.py
- src/simsopt/geo/surfaceobjectives.py
- src/simsopt/geo/surfacerzfourier.py
- src/simsopt/mhd/profiles.py
- src/simsopt/mhd/vmec_diagnostics.py
- src/simsopt/objectives/constrained.py
Newer Python versions throw syntax warnings on import.
This can be avoided by using raw strings or escaping backslashes correctly.
> Silence SyntaxWarnings from unescaped \ in strings
