simsopt/modules/vmec/__init__.py
simsopt/modules/vmec/input.py
simsopt/modules/vmec/output.py

Committing  cleaned up code of Elizabeth Paul's VMEC io processing.

VMEC input and output processing

---

docs/source/conf.py
docs/source/index.rst
docs/source/simsopt.core.rst
docs/source/simsopt.geo.rst
docs/source/simsopt.mhd.rst
docs/source/simsopt.rst
docs/source/simsopt.solve.rst
docs/source/simsopt.util.rst

Simsopt API can be quickly accessed from the TOC

Documentation updated

---

src/simsgeopp/biot_savart.h

noticed this one while installing on a new machine, we don't actually need optional anymore

no optional required

---

src/simsgeopp/python.cpp
src/simsgeopp/reiman.cpp
src/simsopt/geo/magneticfieldclasses.py
tests/geo/test_magneticfields.py

Magnetic field taken from section 5 of Reiman, Greenside (1986), "Calculation of three-dimensional MHD equilibria with islands and stochastic regions", Computer Physics Communications 43 (157-167)
This field has the advantage of allowing an exact calculation of the island width which can be used for island width optimization (example: https://arxiv.org/abs/2102.04497)
What still needs to be added:
- Continuous integration tests
- Optimization example

New magnetic field class: Reiman model

---

docs/source/contributing.rst
docs/source/index.rst

This PR introduces a contributing component to the simsopt documentation. 
Refer to docs/source/contributing.rst.

Docs on contributing

---

docs/source/getting_started.rst

This PR updates the installation intructions to the latest.

Install doc

---

CMakeLists.txt
examples/1_Simple/tracing_fieldline.py
examples/1_Simple/tracing_particle.py
setup.cfg
src/simsoptpp/python_tracing.cpp
src/simsoptpp/tracing.cpp
tests/field/test_fieldline.py
tests/field/test_mpi_tracing.py
tests/field/test_particle.py

This PR downloads and builds the required boost header files if boost is not found. Thereby simsopt wheel will have boost related code functional.

Boost for wheels

---

.github/workflows/ci.yml
.github/workflows/conda.yml
.github/workflows/docker.yml
.github/workflows/wheel.yml
MANIFEST.in
ci/Dockerfile.ubuntu
docs/source/conf.py
pyproject.toml
setup.cfg
setup.py

Auto-versioning by setuptools_scm package.
After a tag is created, for all subsequent commits, setuptools_scm will generate a new version that is dependent on the version specified in the last tag, the number of new commits, and the commit hash. Works for both wheels and sdist.
Addresses #117 and #91

Scm autoversion

---

.github/workflows/ci.yml
.github/workflows/extensive_ci.yml
ci/Dockerfile.ubuntu

This PR tries to fix the issue with simsopt import due to pybind11 related error.

use git submodules in the docker container

---

paper.bib
paper.md

- adds DOIs
- tweaks some minor formatting issues

Minor edits for JOSS review

---

src/simsopt/geo/curvexyzfourier.py

The names were not ordered correctly

fix CurveXYZFourier._make_names

---

.github/workflows/ci.yml
.github/workflows/extensive_ci.yml
.gitmodules
ci/Dockerfile.ubuntu
src/simsopt/mhd/spec.py

This PR reflects the new way to compile SPEC. The CI and extensive CI workflows are updated and the docker image file is updated to build SPEC. The extensive CI is also modified to reduce the number of combinations in dependency installations.

Spec build

---

.github/workflows/extensive_ci.yml
examples/2_Intermediate/QSC.py
src/simsopt/_core/graph_optimizable.py

Converts QSC example to graph framework. The approach shown is the easiest to implement, but requires knowledge of graph Optimizable framework.

Qsc conversion

---

docs/source/getting_started.rst

I updated the installation instructions to include conda installation

Updated installation doc

---

src/simsopt/field/magneticfield.py
tests/field/test_magneticfields.py

throw errors if xyz or rphiz is not c contiguous

---

src/simsopt/geo/jit.py

see https://github.com/google/jax/issues/6805

turn off jax gpu warning

---

.github/workflows/ci.yml
.github/workflows/extensive_ci.yml
src/simsopt/mhd/spec.py

This PR updates the spec imports reflecting the recent updates to SPEC.

spec import updated

---

src/simsopt/mhd/vmec.py
tests/mhd/test_vmec.py

This small change makes it possible to suppress vmec output if desired.

Control vmec printing

---

src/simsopt/field/magneticfieldclasses.py
tests/field/test_magneticfields.py

This PR resolves an issue with the ScalarPotentialRZMagneticField class. The components of B and dB_by_dX were previously returned in cylindrical rather than cartesian coordinates. I have also added a test for the divergence-free condition for a dipole potential.

Fix to ScalarPotentialRZMagneticField

---

.github/workflows/ci.yml
.github/workflows/extensive_ci.yml
src/simsopt/_core/graph_optimizable.py
tests/core/test_graph_optimizable.py

This PR adds a unit test for the plot DAG functionality.

added plot DAG test

---

src/simsopt/_core/graph_optimizable.py
src/simsopt/field/tracing.py
src/simsopt/geo/surfaceobjectives.py
src/simsopt/util/types.py
tests/core/test_graph_optimizable.py

This PR fixes the issues caused by changes in the API's of nptyping.

Nptyping fix

---

.github/workflows/extensive_ci.yml

This PR tries to simplify the tests run under extensive CI to minimize the total time of extensive CI

Reduce extensive CI time

---

.github/workflows/singularity.yml
MANIFEST.in

Thirdparty folders are now included into the source distribution uploaded to pypa.

Add thirdparty folders to sdist

---

.vscode/settings.json
docs/source/example_coils.rst
examples/2_Intermediate/stage_two_optimization.py

In this PR, the novel features of stage2 optimization in SIMSOPT are documented.
Namely it is added documentation on:
- Stochastic optimization
- Finite beta optimization
- Finite build optimization
The documentation follows the examples provided in the examples folder.

Expanded coil documentation

---

.github/workflows/ci.yml
.github/workflows/extensive_ci.yml

Not sure how this regressed but added py_spec installation in CI to prevent the CI failures.

Spec CI fix

---

src/simsopt/_core/derivative.py

Minor fix in derivative documentation.

Bug fix in deriv doc

---

src/simsopt/_core/json.py
src/simsopt/field/magneticfieldclasses.py
tests/field/test_magneticfields.py

fix for failing unit test in Extensive CI #1089
@mbkumar consider adding the other fixes to this PR

fix for failing unit tests

---

src/simsopt/geo/surfacerzfourier.py
tests/geo/test_surface_rzfourier.py

Fix memory leak and appropriate test

PR: Fix memory leak bug in from_pyQSC

---

docs/source/example_single_stage.rst
src/simsopt/solve/permanent_magnet_optimization.py
src/simsopt/util/polarization_project.py

Fixes the issues raised in #329

Fixes the permanent magnet docstring for sphinx

---

src/simsopt/mhd/vmec.py

- free-boundary parameters included in VMEC input file
- ntheta, nzeta resolution parameters included in VMEC input file

additional VMEC input file parameters

---

.github/workflows/docs_test.yml
setup.cfg

This CI is to catch failures when building the docs.

CI for docs

---

src/simsopt/field/magneticfieldclasses.py
src/simsopt/geo/curveperturbed.py

Update for scipy 1.11.2, hopefully fixing #349

scipy sqrtm fix

---

setup.cfg

Change the license to MIT in setup.cfg

---

.github/workflows/conda.yml
.github/workflows/docker.yml
.github/workflows/docs_test.yml
.github/workflows/extensive_test.yml
.github/workflows/linting.yml
.github/workflows/non_simd_tests.yml
.github/workflows/singularity.yml
.github/workflows/tests.yml
.github/workflows/wheel.yml

The recommended versions for many Actions used in the workflows have been changed. This PR brings the Actions versions to the latest ones.

Version bump for various Actions used in Workflows

---

src/simsoptpp/magneticfield.h
src/simsoptpp/python_magneticfield.cpp
tests/field/test_magneticfields.py

Implemented magnetic potential in cylindrical coordinates.
No tests are added. Let me know if tests are needed for this.

Implement magnetic potential in cylindrical coordinates

---

src/simsopt/geo/__init__.py
src/simsopt/geo/curveobjectives.py
src/simsoptpp/python_distance.cpp
tests/geo/test_curve_objectives.py

This PR speeds up the `LinkingNumber` objective for coil optimization by moving more of the python to C++, adding OpenMP, and adding an option to downsample the quadrature points.

Speed up LinkingNumber

---

.github/workflows/singularity.yml
ci/Dockerfile.ubuntu
ci/singularity.def

Resolves #424 
This fix was based on the recommended solution at https://stackoverflow.com/questions/52547833/getting-importerror-libxrender-so-1-cannot-open-shared-object-file-when-impo

Fix mayavi install failure in Docker and Singularity containers

---

src/simsopt/util/polarization_project.py

Replaced with equivalent numpy operation

removed deprecated use of import numpy.matlib

---

src/simsopt/objectives/constrained.py

As part of **Fix-It week 2025**.
Fixed the documentation of the `ConstrainedProblem` class. Included arguments and types for each function, corrected broken latex, and used proper styling.
See image of corrected documentation.
\
\
**Tests**
No tests are needed since this is a documentation fix.

(Fix-It Week) Fixed Documentation for ConstrainedProblem

---

docs/source/example_derivative.rst
docs/source/index.rst

**PR part of Fix-It Week 2025**
In this PR, we add a new section to the ReadTheDocs sidebar: the "Developer Guides". The Developer Guides section is meant to hold tutorials to help developers build code with SIMSOPT's features. As the first tutorial in the developer guides we added the "Using the Derivative class" tutorial, which teaches developers how to build an objective function with derivatives in SIMSOPT. Learning how to add derivatives to Optimizable objects has been a challenge for many developers, in our experience.
Attached are two screenshots showing the new entry in the sidebar and the tutorial.
\
\
**Tests**
No tests are needed since this is a documentation fix.

Developer Guides with Derivative Tutorial

---

examples/2_Intermediate/permanent_magnet_MUSE.py
examples/2_Intermediate/permanent_magnet_QA.py
src/simsopt/util/permanent_magnet_helper_functions.py
tests/geo/test_pm_grid.py

As title describes, this pull request merely renames the function in permanent_magnet_helpers.py and makes some other little changes in the comments and docstring to make it clear.

Rename calculate_on_axis_B function

---

pyproject.toml
src/simsopt/__init__.py
src/simsopt/_core/util.py
src/simsopt/objectives/functions.py

Prune unused code

---

tests/geo/test_wireframe_toroidal.py
tests/solve/test_wf_optimization.py

Added minor coverage improvements to wireframe functionality, mostly checking ValueError throws

Added wf coverage increases.
